/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 shoe.gltf --transform
Author: Allay Design (https://sketchfab.com/Alister.Dsouza)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cowboy-shoes-9424d591a1324a18945eae010c0bd169
Title: Cowboy -  Shoes
*/

import React, { useEffect } from 'react'
import { Decal, useGLTF, useTexture } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";
import { easing } from "maath";
import { useSnapshot } from "valtio";
import state from "../store";

export default function Model(props) {

  const { nodes, materials } = useGLTF('/shoe2-transformed.glb')

  const snap = useSnapshot(state);
  const fullTexture = useTexture(snap.fullDecal)

  useFrame((state, delta) => {
    easing.dampC(materials.blinn8SG.color, snap.color, 0.25, delta)
    if (snap.isMetallic){
      materials.blinn8SG.roughness = 0;
      materials.blinn8SG.metalness = 0.5;
    } else {
      materials.blinn8SG.roughness = 0.5;
      materials.blinn8SG.metalness = 0;
    }
    if (snap.isWireframe){
      materials.blinn8SG.wireframe = true;
    } else {
      materials.blinn8SG.wireframe = false;
    }
  })
  const stateString = JSON.stringify(snap)

  return (
    <group {...props} dispose={null} key={stateString}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.defaultMaterial.geometry} material={materials.blinn8SG} rotation={[Math.PI / 2, 0, 0]} >
        {snap.isFullTexture && (
          <Decal 
            position={[1, 18.81, 3.17]}
            rotation={[0, 0, 0]}
            scale={75}
            map={fullTexture}
            map-anisotropy={16}
          />
        )}
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/shoe2-transformed.glb')
