/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 shoe.gltf --transform
Author: ThePro97 (https://sketchfab.com/ThePro97)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-shoes-c100d8b9e4684e6e9be20c16c74cc257
Title: Old Shoes
*/

import React, { useRef } from 'react'
import { Decal, useGLTF, useTexture } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";
import { easing } from "maath";
import { useSnapshot } from "valtio";
import state from "../store";

export default function Model(props) {
  const { nodes, materials } = useGLTF('/shoe3-transformed.glb')

  const snap = useSnapshot(state);
  const fullTexture = useTexture(snap.fullDecal)

  useFrame((state, delta) => {
    easing.dampC(materials.Old_Shoes.color, snap.color, 0.25, delta)
    if (snap.isMetallic){
      materials.Old_Shoes.roughness = 0;
      materials.Old_Shoes.metalness = 0.5;
    } else {
      materials.Old_Shoes.roughness = 0.5;
      materials.Old_Shoes.metalness = 0;
    }
    if (snap.isWireframe){
      materials.Old_Shoes.wireframe = true;
    } else {
      materials.Old_Shoes.wireframe = false;
    }
  })
  const stateString = JSON.stringify(snap)

  return (
    <group {...props} dispose={null} key={stateString}>
      <group rotation={[-Math.PI / 2, 0, 0]} position={[0.03, -45.86, 0.63]} castShadow>
        <group position={[54.03, 88.86, 0.63]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.Old_Shoes} position={[-84.03, -88.86, -0.63]} >
          {snap.isFullTexture && (
            <Decal
              position={[124.03, 180.86, 0.63]}
              rotation={[0, 0, 0]}
              scale={555}
              map={fullTexture}
            />
          )}
          </mesh>
        </group>
        <group position={[-66.12, 88.86, 0.63]}>
          <mesh geometry={nodes.Object_7.geometry} material={materials.Old_Shoes} position={[66.12, -88.86, -0.63]}>
          {snap.isFullTexture && (
            <Decal
              position={[124.03, 180.86, 0.63]}
              rotation={[0, 0, 0]}
              scale={555}
              map={fullTexture}
            />
          )}
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/shoe3-transformed.glb')
