/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 shoe.gltf --transform
Author: Virtual Museums of Małopolska (https://sketchfab.com/WirtualneMuzeaMalopolski)
License: CC0-1.0 (http://creativecommons.org/publicdomain/zero/1.0/)
Source: https://sketchfab.com/3d-models/priest-karol-wojtyas-sports-shoes-678f96cfadc741a3b260548eeb75954a
Title: Priest Karol Wojtyła’s sports shoes
*/

import React, { useRef } from "react";
import { Decal, useGLTF, useTexture } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { easing } from "maath";
import { useSnapshot } from "valtio";
import state from "../store";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/shoe-transformed.glb");

  const group = useRef();
  const snap = useSnapshot(state);
  const fullTexture = useTexture(snap.fullDecal);
  const isBreakpoint = window.innerWidth <= 1260;
  const isMobile = window.innerWidth <= 600;

  let targetPosition = [0, 1.81, 11.17];

  useFrame((state, delta) => {
    // set the inital position of the model
    if (snap.intro) {
      if (isBreakpoint) targetPosition = [0, -10.81, 1.17];
      if (isMobile) targetPosition = [0, -15.81, 1.17];
    } else {
      if (isMobile) targetPosition = [0, 1.81, 1.17];
      else targetPosition = [0, 1.81, 1.17];
    }

    // set model camera position
    easing.damp3(group.current.position, targetPosition, 0.25, delta);

    easing.dampC(materials.defaultMat.color, snap.color, 0.25, delta);
    if (snap.isMetallic){
      materials.defaultMat.roughness = 0;
      materials.defaultMat.metalness = 0.5;
    } else {
      materials.defaultMat.roughness = 0.5;
      materials.defaultMat.metalness = 0;
    }
    if (snap.isWireframe){
      materials.defaultMat.wireframe = true;
    } else {
      materials.defaultMat.wireframe = false;
    }
  });
  const stateString = JSON.stringify(snap);

  return (
    <group {...props} dispose={null} key={stateString}>
      <group ref={group} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Sphere001_defaultMat_0.geometry}
          material={materials.defaultMat}
          rotation={[-Math.PI, 0, 0]}
        >
          {snap.isFullTexture && (
            <Decal
              position={[5, -18.81, 1.17]}
              rotation={[0, 0, 0]}
              scale={55}
              map={fullTexture}
            />
          )}
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/shoe-transformed.glb");
